---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: ecommerce
spec:
  selector:
    app: jaeger
  ports:
    - name: collector-http
      port: 14268
      targetPort: 14268
    - name: collector-grpc
      port: 14250
      targetPort: 14250
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: ui
      port: 16686
      targetPort: 16686
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.52
          ports:
            - containerPort: 14268
            - containerPort: 14250
            - containerPort: 4317
            - containerPort: 16686
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"