apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - mongodb.yaml
  - redis.yaml
  - opensearch.yaml
  - jaeger.yaml
  - otel-collector.yaml
  - flagd.yaml
  - flagd-realistic.yaml
  - user-service.yaml
  - product-service.yaml
  - cart-service.yaml
  - frontend.yaml
  - nginx.yaml