---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ecommerce
type: Opaque
stringData:
  password: postgres123

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: ecommerce
type: Opaque
stringData:
  password: admin123

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: ecommerce
type: Opaque
stringData:
  password: redis123